# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  BEATS_PROJECT_NAME: "heartbeat"
  IMAGE_UBUNTU_X86_64: "family/platform-ingest-beats-ubuntu-2204"
  AWS_IMAGE_UBUNTU_ARM_64: "platform-ingest-beats-ubuntu-2004-aarch64"
  IMAGE_WIN_2016: "family/core-windows-2016"
  IMAGE_WIN_2019: "family/core-windows-2019"
  IMAGE_WIN_2022: "family/core-windows-2022"
  IMAGE_RHEL9: "family/platform-ingest-beats-rhel-9"
  IMAGE_MACOS_X86_64: "generic-13-ventura-x64"
  GCP_DEFAULT_MACHINE_TYPE: "c2d-highcpu-8"
  GCP_HI_PERF_MACHINE_TYPE: "c2d-highcpu-16"
  GCP_WIN_MACHINE_TYPE: "n2-standard-8"
  AWS_ARM_INSTANCE_TYPE: "t4g.xlarge"

steps:
  - group: "Heartbeat Mandatory Testing"
    key: "heartbeat-mandatory-tests"
    steps:
      - label: ":linux: Heartbeat Unit Tests / {{matrix.image}}"
        command: ".buildkite/heartbeat/scripts/unit-tests.sh"
        agents:
          provider: "gcp"
          image: "{{matrix.image}}"
          machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
        matrix:
          setup:
            image:
              - "${IMAGE_UBUNTU_X86_64}"
              - "${IMAGE_RHEL9}"
        artifact_paths:
          - "heartbeat/build/*.xml"
          - "heartbeat/build/*.json"

      - label: ":windows: Heartbeat Unit Tests / {{matrix.image}}"
        command: ".buildkite/scripts/win_unit_tests.ps1"
        agents:
          provider: "gcp"
          image: "{{matrix.image}}"
          machine_type: "${GCP_WIN_MACHINE_TYPE}"
          disk_type: "pd-ssd"
        matrix:
          setup:
            image:
              - "${IMAGE_WIN_2016}"
              - "${IMAGE_WIN_2022}"
        artifact_paths:
          - "heartbeat/build/*.xml"
          - "heartbeat/build/*.json"

      - label: ":ubuntu: Heartbeat Go Integration Tests"
        command: ".buildkite/heartbeat/scripts/integration-gotests.sh"
        agents:
          provider: "gcp"
          image: "${IMAGE_UBUNTU_X86_64}"
          machineType: "${GCP_HI_PERF_MACHINE_TYPE}"
        artifact_paths:
          - "heartbeat/build/*.xml"
          - "heartbeat/build/*.json"

      - label: ":ubuntu: Heartbeat Python Integration Tests"
        command: ".buildkite/heartbeat/scripts/integration-pytests.sh"
        agents:
          provider: "gcp"
          image: "${IMAGE_UBUNTU_X86_64}"
          machineType: "${GCP_HI_PERF_MACHINE_TYPE}"
        artifact_paths:
          - "heartbeat/build/*.xml"
          - "heartbeat/build/*.json"

  - group: "Heartbeat ARM Tests"
    key: "heartbeat-extended-tests-arm"
    if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*arm.*/
    steps:
      - label: ":linux: Heartbeat ARM64 Unit Tests"
        key: "heartbeat-arm-extended"
        command: ".buildkite/heartbeat/scripts/unit-tests.sh"
        agents:
          provider: "aws"
          imagePrefix: "${AWS_IMAGE_UBUNTU_ARM_64}"
          instanceType: "${AWS_ARM_INSTANCE_TYPE}"
        artifact_paths: "heartbeat/build/*.xml"

  - group: "Heartbeat Extended Testing MacOS"
    key: "heartbeat-extended-tests-macos"
    if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*macOS.*/
    steps:
      - label: ":mac: MacOS Unit Tests"
        key: "heartbeat-macos-extended"
        command: ".buildkite/heartbeat/scripts/unit-tests.sh"
        agents:
          provider: "orka"
          imagePrefix: "${IMAGE_MACOS_X86_64}"
        artifact_paths: "heartbeat/build/*.xml"

  - group: "Heartbeat Windows Extended Testing"
    key: "heartbeat-extended-tests-win"
    if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_LABELS") =~ /.*windows.*/

    steps:
      - label: ":windows: Win 2019 Unit Tests"
        key: "heartbeat-win-extended-2019"
        command: ".buildkite/scripts/win_unit_tests.ps1"
        agents:
          provider: "gcp"
          image: "${IMAGE_WIN_2019}"
          machine_type: "${GCP_WIN_MACHINE_TYPE}"
          disk_type: "pd-ssd"
        artifact_paths:
          - "heartbeat/build/*.xml"
          - "heartbeat/build/*.json"

  - group: "Heartbeat Packaging"
    key: "heartbeat-packaging"
    if: build.env("BUILDKITE_PULL_REQUEST") != "false" || build.env("GITHUB_PR_TRIGGER_COMMENT") == "/package"
    depends_on:
      - "heartbeat-mandatory-tests"
    steps:
      - label: ":ubuntu: Heartbeat/Packaging Linux X86"
        key: "heartbeat-package-linux-x86"
        env:
          PLATFORMS: "+all linux/amd64 linux/arm64 windows/amd64 darwin/amd64 darwin/arm64"
          SNAPSHOT: true
        command: ".buildkite/scripts/packaging/package.sh"
        agents:
          provider: gcp
          image: "${IMAGE_UBUNTU_X86_64}"
          machineType: "${GCP_HI_PERF_MACHINE_TYPE}"

      - label: ":linux: Heartbeat/Packaging Linux ARM"
        key: "heartbeat-package-linux-arm"
        env:
          PLATFORMS: "linux/arm64"
          PACKAGES: "docker"
          SNAPSHOT: true
        command: ".buildkite/scripts/packaging/package.sh"
        agents:
          provider: "aws"
          imagePrefix: "${AWS_IMAGE_UBUNTU_ARM_64}"
          instanceType: "${AWS_ARM_INSTANCE_TYPE}"
