# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
name: "beats-auditbeat"

env:
  AWS_IMAGE_UBUNTU_ARM_64: "platform-ingest-beats-ubuntu-2004-aarch64"
  IMAGE_UBUNTU_X86_64: "family/platform-ingest-beats-ubuntu-2204"
  IMAGE_UBUNTU_ARM_64: "platform-ingest-beats-ubuntu-2204-aarch64"
  IMAGE_RHEL9: "family/platform-ingest-beats-rhel-9"
  IMAGE_WIN_10: "family/platform-ingest-beats-windows-10"
  IMAGE_WIN_11: "family/platform-ingest-beats-windows-11"
  IMAGE_WIN_2016: "family/platform-ingest-beats-windows-2016"
  IMAGE_WIN_2019: "family/platform-ingest-beats-windows-2019"
  IMAGE_WIN_2022: "family/platform-ingest-beats-windows-2022"
  IMAGE_MACOS_X86_64: "generic-13-ventura-x64"
  BEATS_PROJECT_NAME: "auditbeat"
  GCP_DEFAULT_MACHINE_TYPE: "c2d-highcpu-8"
  GCP_HI_PERF_MACHINE_TYPE: "c2d-highcpu-16"
  GCP_WIN_MACHINE_TYPE: "n2-standard-8"
  AWS_ARM_INSTANCE_TYPE: "t4g.xlarge"

steps:
  - group: "Auditbeat Mandatory Testing"
    key: "mandatory-tests"

    steps:
      - label: ":ubuntu: Unit Tests"
        command:
          - ".buildkite/auditbeat/scripts/unit-tests.sh"
        notify:
          - github_commit_status:
              context: "Auditbeat: linux/Unit Tests"
        agents:
          provider: "gcp"
          image: "${IMAGE_UBUNTU_X86_64}"
          machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
        artifact_paths:
          - "auditbeat/build/*.xml"
          - "auditbeat/build/*.json"

      - label: ":rhel: Unit Tests"
        command:
          - ".buildkite/auditbeat/scripts/unit-tests.sh"
        notify:
          - github_commit_status:
              context: "Auditbeat: rhel/Unit Tests"
        agents:
          provider: "gcp"
          image: "${IMAGE_RHEL9}"
          machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
        artifact_paths:
          - "auditbeat/build/*.xml"
          - "auditbeat/build/*.json"

      - label: ":windows:-2016 Unit Tests"
        command: ".buildkite/scripts/win_unit_tests.ps1"
        notify:
          - github_commit_status:
              context: "Auditbeat: windows 2016/Unit Tests"
        agents:
          provider: "gcp"
          image: "${IMAGE_WIN_2016}"
          machine_type: "${GCP_WIN_MACHINE_TYPE}"
          disk_size: 200
          disk_type: "pd-ssd"
        artifact_paths:
          - "auditbeat/build/*.xml"
          - "auditbeat/build/*.json"

      - label: ":windows:-2022 Unit Tests"
        command: ".buildkite/scripts/win_unit_tests.ps1"
        notify:
          - github_commit_status:
              context: "Auditbeat: windows 2022/Unit Tests"
        agents:
          provider: "gcp"
          image: "${IMAGE_WIN_2022}"
          machine_type: "${GCP_WIN_MACHINE_TYPE}"
          disk_size: 200
          disk_type: "pd-ssd"
        artifact_paths:
          - "auditbeat/build/*.xml"
          - "auditbeat/build/*.json"

      - label: ":linux: Crosscompile"
        command:
          - ".buildkite/auditbeat/scripts/crosscompile.sh"
        env:
          GOX_FLAGS: "-arch amd64"
        notify:
          - github_commit_status:
              context: "Auditbeat: Crosscompile"
        agents:
          provider: "gcp"
          image: "${IMAGE_UBUNTU_X86_64}"
          machineType: "${GCP_HI_PERF_MACHINE_TYPE}"

  - group: "Extended Tests"
    key: "extended-tests-arm"
    if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.pull_request.labels includes "arm"
    steps:
      - label: ":arm: ARM64 Unit Tests"
        key: "extended-arm64-unit-tests"
        command: ".buildkite/scripts/unit_tests.sh"
        agents:
          provider: "gcp"
          image: "${IMAGE_UBUNTU_ARM64}"
          machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
        artifact_paths: "${BEATS_PROJECT_NAME}/build/*.*"
        notify:
          - github_commit_status:
              context: "Auditbeat: ARM Unit tests"

  - group: "Windows Extended Testing"
    key: "extended-tests-win"
    if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.pull_request.labels includes "windows"
    steps:
      - label: ":windows: Windows 2019 Unit Tests"
        key: "extended-win-2019-unit-tests"
        command: ".buildkite/scripts/win_unit_tests.ps1"
        agents:
          provider: "gcp"
          image: "${IMAGE_WIN_2019}"
          machine_type: "${GCP_WIN_MACHINE_TYPE}"
          disk_size: 100
          disk_type: "pd-ssd"
        artifact_paths: "${BEATS_PROJECT_NAME}/build/*.*"
        notify:
          - github_commit_status:
              context: "Auditbeat: Windows 2019 Unit Tests"

      - label: ":windows: Windows 10 Unit Tests"
        key: "extended-win-10-unit-tests"
        command: ".buildkite/scripts/win_unit_tests.ps1"
        agents:
          provider: "gcp"
          image: "${IMAGE_WIN_10}"
          machine_type: "${GCP_WIN_MACHINE_TYPE}"
          disk_size: 100
          disk_type: "pd-ssd"
        artifact_paths: "${BEATS_PROJECT_NAME}/build/*.*"
        notify:
          - github_commit_status:
              context: "Auditbeat: Windows 10 Unit Tests"

      - label: ":windows: Windows 11 Unit Tests"
        key: "extended-win-11-unit-tests"
        command: ".buildkite/scripts/win_unit_tests.ps1"
        agents:
          provider: "gcp"
          image: "${IMAGE_WIN_11}"
          machine_type: "${GCP_WIN_MACHINE_TYPE}"
          disk_size: 100
          disk_type: "pd-ssd"
        artifact_paths: "${BEATS_PROJECT_NAME}/build/*.*"
        notify:
          - github_commit_status:
              context: "Auditbeat: Windows 11 Unit Tests"
  - group: "Packaging"
    key: "packaging"
    if: build.env("BUILDKITE_PULL_REQUEST") == "false" || build.env("GITHUB_PR_TRIGGER_COMMENT") == "/package"
    depends_on:
      - "mandatory-tests"
    steps:
      - label: Package pipeline
        commands: ".buildkite/scripts/packaging/package-step.sh"
        notify:
          - github_commit_status:
              context: "Auditbeat: Packaging"
