# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  ASDF_MAGE_VERSION: 1.15.0
  IMAGE_UBUNTU_X86_64: "family/platform-ingest-beats-ubuntu-2204"

steps:
  - group: ":Packaging Artifacts"
    key: "package"
    steps:
      - label: ":package: Cross Building and package agentbeat"
        key: package_agentbeat
        agents:
          provider: "gcp"
          machineType: "c2-standard-16"
          image: "${IMAGE_UBUNTU_X86_64}"
          diskSizeGb: 400
        command: |
          sudo apt-get update -y
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends --yes msitools
          cd x-pack/agentbeat && mage package

        env:
          SNAPSHOT: true

        artifact_paths:
          - "x-pack/agentbeat/build/distributions/**/*"

      - label: ":elastic-stack: Publishing to DRA Snapshot"
        key: dra-publish
        depends_on: package_agentbeat
        agents:
          provider: "gcp"
        command: |
          echo "+++ Restoring Artifacts"
          buildkite-agent artifact download "x-pack/agentbeat/build/distributions/**/*" . --build 018ee250-9584-4296-b538-c64ff891c023

          echo "+++ Changing permissions for the release manager"
          sudo chown -R :1000 build/distributions/

          echo "+++ :hammer_and_pick: Publishing DRA artifacts..."
          .buildkite/x-pack/agentbeat/scripts/dra.sh
        env:
          DRA_WORKFLOW: snapshot
